version: '3'
services:
  bench:
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    privileged: true  # Needed for pcap
    volumes:
      - cargo-cache:/usr/local/cargo/registry
    security_opt:
      - no-new-privileges:false

volumes:
  cargo-cache: